#!/bin/bash

# argv
pseudo_recipient=$1
pseudo_bot=$2
if [[ -z $pseudo_bot ]]; then
    pseudo_bot="bot"
fi

#conditions
function error_handling(){
    if [[ -z $pseudo_recipient ]]; then # TODO selon les consignes faire pour un number incorrect de parametre donc plus que 2 aussi?
        echo "chat-bot destinataire [pseudo]"
        exit 1
    fi
}

#responses
function commands_responses(){
    case $1 in
    "liste") echo "1";;
    "li") echo "2";;
    "qui suis-je") echo "3";;
    "au revoir") echo "4";;
    esac
}

# input loop
function bot_loop(){
    while true;
    do
        read -p "Entre command: " var # input
        commands_responses $var
    done
}

# main function
function main(){
    error_handling
    bot_loop
}
main
