#!/bin/bash

# argv
pseudo_recipien=$1
pseudo_bot=$2

#responses
function commands_responses(){
    case $1 in
    "liste") echo "1";;
    "li") echo "2";;
    "qui suis-je") echo "3";;
    "au revoir") echo "4";;
    esac
}

# input loop
while true;
do
    read -p "Entre command: " var # input
    commands_responses $var
done
